package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

import javax.swing.JOptionPane;

import model.Admin;

public class AdminLogin extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public AdminLogin() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		title = new javax.swing.JLabel();
		adminNo = new javax.swing.JLabel();
		adminNoField = new javax.swing.JTextField();
		password = new javax.swing.JLabel();
		passwordField = new javax.swing.JPasswordField();
		loginButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		title.setFont(new java.awt.Font("Dialog", 1, 14));
		title.setText("Administrator Login");

		adminNo.setFont(new java.awt.Font("Dialog", 1, 12));
		adminNo.setText("Admin No.");

		password.setFont(new java.awt.Font("Dialog", 1, 12));
		password.setText("Password");

		loginButton.setFont(new java.awt.Font("Dialog", 1, 12));
		loginButton.setText("login");
		loginButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				login();
				passwordField.setText("");
			}
		});

		resetButton.setFont(new java.awt.Font("Dialog", 1, 12));
		resetButton.setText("reset");
		resetButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				adminNoField.setText("");
				passwordField.setText("");
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(64, 64,
																		64)
																.addComponent(
																		title,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(35, 35,
																		35)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						adminNo,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						71,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						password,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						60,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						loginButton,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																								.addComponent(
																										passwordField,
																										javax.swing.GroupLayout.Alignment.LEADING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										103,
																										Short.MAX_VALUE)
																								.addComponent(
																										adminNoField,
																										javax.swing.GroupLayout.Alignment.LEADING,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										103,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										resetButton,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(13,
																										13,
																										13)))))
								.addContainerGap(61,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(title,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														adminNo,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														adminNoField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														password,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														passwordField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(20, 20, 20)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														loginButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														resetButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(32, 32, 32)));

		title.getAccessibleContext().setAccessibleName("");

		pack();
		setVisible(true);
	}
	
	/**
	 * the operation for loginButton
	 */
	private void login(){
		if (!"".equals(adminNoField.getText()) && !"".equals(passwordField.getText())) {
			Integer id = new Integer(adminNoField.getText());
			String password = passwordField.getText();
			Admin admin = getLoginAdmin(id, password);
			if (admin != null) {
				JOptionPane.showMessageDialog(null, "welcom,"+admin.getName());
				MainMenu.mainMenu = new MainMenu();
				MainMenu.mainMenu.adminInfo.setText("Hello,"+admin.getName()+"   AdminNo."+admin.getId());
				if(!admin.isManager()){
					MainMenu.mainMenu.editSatus.setEnabled(false);
					MainMenu.mainMenu.chargePolicy.setEnabled(false);
					MainMenu.mainMenu.changePassword.setEnabled(false);
				}
				AdminLogin.adminLogin.dispose();
			} else {
				JOptionPane.showMessageDialog(null, "No or password is wrong");
			}
		}else {
			JOptionPane.showMessageDialog(null, "No and password can't be null");
		}
	}
	
	/**
	 * find exact admin
	 * @param id
	 * @param password
	 * @return
	 */
	private Admin getLoginAdmin(Integer id, String password){
		try {
			BufferedReader reader = new BufferedReader(new FileReader(new File("src/admin.txt")));
			String adminInfo = null;
			Admin admin = new Admin();
			while (!"".equals((adminInfo = reader.readLine()))&&adminInfo!=null) {
				String[] adminInfos = adminInfo.split("@");
				if (id.toString().equals(adminInfos[0]) && password.equals(adminInfos[1])) {
					admin.setId(id);
					admin.setPassword(password);
					if (adminInfos[2].equals("1")) {
						admin.setManager(true);
					} else {
						admin.setManager(false);
					}
					admin.setName(adminInfos[3]);
					return admin;
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

	// Variables declaration - do not modify
	public static AdminLogin adminLogin;
	private javax.swing.JLabel adminNo;
	private javax.swing.JTextField adminNoField;
	private javax.swing.JButton loginButton;
	private javax.swing.JLabel password;
	private javax.swing.JTextField passwordField;
	private javax.swing.JButton resetButton;
	private javax.swing.JLabel title;
	// End of variables declaration//GEN-END:variables

}
