package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import control.Sytem;


public class EditStatus extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form EditStatus */
	public EditStatus() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		title = new javax.swing.JLabel();
		space = new javax.swing.JLabel();
		spaceField = new javax.swing.JTextField();
		status = new javax.swing.JLabel();
		weekdayBox = new javax.swing.JCheckBox();
		holidayBox = new javax.swing.JCheckBox();
		doneButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		title.setFont(new java.awt.Font("微软雅黑", 1, 14));
		title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		title.setText("EDIT  STATUS");

		space.setFont(new java.awt.Font("微软雅黑", 1, 12));
		space.setText("SUM PARKING SPACE :");

		spaceField.setFont(new java.awt.Font("微软雅黑", 1, 12));

		status.setFont(new java.awt.Font("微软雅黑", 1, 12));
		status.setText("STATUS :");

		weekdayBox.setFont(new java.awt.Font("微软雅黑", 1, 12));
		weekdayBox.setText("WEEKDAYS(FOR STAFF ONLY)");

		holidayBox.setFont(new java.awt.Font("微软雅黑", 1, 12));
		holidayBox.setText("WEEKENDS/HOLIDAYS/SUMMERTIME(OPEN TO PUBLIC)");

		doneButton.setFont(new java.awt.Font("微软雅黑", 1, 12));
		doneButton.setText("DONE");
		doneButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				String count = spaceField.getText();
				if (!"".equals(count)) {
					int spaceCount = Integer.parseInt(count);
					Sytem.spaceCount = spaceCount;
					JOptionPane.showMessageDialog(null, "save success");
				}else if(weekdayBox.isSelected()||holidayBox.isSelected()) {
					JOptionPane.showMessageDialog(null, "save success");
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(space,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										153,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(spaceField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										98,
										javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(status)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						holidayBox)
																				.addComponent(
																						weekdayBox)))))
				.addGroup(
						layout.createSequentialGroup().addGap(136, 136, 136)
								.addComponent(title))
				.addGroup(
						layout.createSequentialGroup().addGap(157, 157, 157)
								.addComponent(doneButton)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(14, 14, 14)
								.addComponent(title)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														spaceField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(space))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(status)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(weekdayBox)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(holidayBox)
								.addGap(50, 50, 50)
								.addComponent(doneButton)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
		setVisible(true);
	}



	// Variables declaration - do not modify
	public static EditStatus editStatus;
	private javax.swing.JButton doneButton;
	private javax.swing.JCheckBox holidayBox;
	private javax.swing.JLabel space;
	private javax.swing.JTextField spaceField;
	private javax.swing.JLabel status;
	private javax.swing.JLabel title;
	private javax.swing.JCheckBox weekdayBox;
	// End of variables declaration//GEN-END:variables

}
