package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form StaffRegister */
	public Register() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		title = new javax.swing.JLabel();
		campusId = new javax.swing.JLabel();
		name = new javax.swing.JLabel();
		motoNo = new javax.swing.JLabel();
		motoType = new javax.swing.JLabel();
		color = new javax.swing.JLabel();
		campusIdField = new javax.swing.JTextField();
		nameField = new javax.swing.JTextField();
		motoNoField = new javax.swing.JTextField();
		motoTypeField = new javax.swing.JTextField();
		colorField = new javax.swing.JTextField();
		registerButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();
		motoNo1 = new javax.swing.JLabel();
		motoNoField2 = new javax.swing.JTextField();
		motoNo2 = new javax.swing.JLabel();
		motoNoField3 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		title.setFont(new java.awt.Font("Dialog", 1, 14));
		title.setText("Register");

		campusId.setText("CAMPUS ID");

		name.setText("NAME");

		motoNo.setText("MOTO NO");

		motoType.setText("MOTO TYPE");

		color.setText("COLOR");

		registerButton.setText("REGISTER");
		registerButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				register();
			}
		});

		resetButton.setText("RESET");
		resetButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				campusIdField.setText("");
				nameField.setText("");
				motoTypeField.setText("");
				motoNoField.setText("");
				motoNoField2.setText("");
				motoNoField3.setText("");
				colorField.setText("");
			}
		});

		motoNo1.setText("MOTO NO2");

		motoNo2.setText("MOTO NO3");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(90, 90,
																		90)
																.addComponent(
																		title))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(28, 28,
																		28)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						motoNo1)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										campusId)
																								.addComponent(
																										name)
																								.addComponent(
																										motoNo,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										70,
																										Short.MAX_VALUE))
																				.addComponent(
																						motoNo2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						motoNoField3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						86,
																						Short.MAX_VALUE)
																				.addComponent(
																						motoNoField2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						86,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																								.addComponent(
																										campusIdField,
																										javax.swing.GroupLayout.Alignment.LEADING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										82,
																										Short.MAX_VALUE)
																								.addComponent(
																										nameField)
																								.addComponent(
																										motoNoField)))
																.addGap(8, 8, 8)))
								.addGap(85, 85, 85))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(16,
																						16,
																						16)
																				.addComponent(
																						color))
																.addComponent(
																		registerButton))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		motoType)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														colorField,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														86, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(25, 25,
																		25)
																.addComponent(
																		resetButton))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		motoTypeField,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		86,
																		Short.MAX_VALUE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
								.addGap(87, 87, 87)));

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { campusIdField, colorField,
						motoNoField, motoNoField2, motoNoField3, motoTypeField,
						nameField });

		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(title)
								.addGap(14, 14, 14)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(campusIdField, 0,
														0, Short.MAX_VALUE)
												.addComponent(campusId))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(nameField, 0, 0,
														Short.MAX_VALUE)
												.addComponent(name))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(motoNo)
												.addComponent(motoNoField, 0,
														0, Short.MAX_VALUE))
								.addGap(6, 6, 6)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(motoNo1)
												.addComponent(motoNoField2, 0,
														0, Short.MAX_VALUE))
								.addGap(7, 7, 7)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(motoNo2)
												.addComponent(
														motoNoField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														17, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(motoType)
												.addComponent(
														motoTypeField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														17,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(color)
												.addComponent(
														colorField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														17,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(resetButton)
												.addComponent(registerButton))
								.addGap(24, 24, 24)));

		pack();
		setVisible(true);
	}
	
	private void register(){
		String campusId = campusIdField.getText();
		String name = nameField.getText();
		String motoNo = motoNoField.getText();
		String motoNo2 = motoNoField2.getText();
		String motoNo3 = motoNoField3.getText();
		String motoType = motoTypeField.getText();
		String color = colorField.getText();
		if (!"".equals(campusId) && !"".equals(name) && !"".equals(motoNo)) {
			String staff = campusId+"@"+name+"@"+motoNo+","+motoNo2+","+motoNo3+"@"+motoType+"@"+color+"@"+"0";
			try {
				BufferedWriter writer = new BufferedWriter(new FileWriter(new File("src/staff.txt"),true));
				writer.write(staff);
				writer.newLine();
				writer.flush();
				writer.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
			JOptionPane.showMessageDialog(null, "register success");
			Register.register.dispose();
		} else {
			JOptionPane.showMessageDialog(null, "imperfect staff info");
		}
	}

	// Variables declaration - do not modify
	public static Register register;
	private javax.swing.JLabel campusId;
	private javax.swing.JTextField campusIdField;
	private javax.swing.JLabel color;
	private javax.swing.JTextField colorField;
	private javax.swing.JLabel motoNo;
	private javax.swing.JLabel motoNo1;
	private javax.swing.JLabel motoNo2;
	private javax.swing.JTextField motoNoField;
	private javax.swing.JTextField motoNoField2;
	private javax.swing.JTextField motoNoField3;
	private javax.swing.JLabel motoType;
	private javax.swing.JTextField motoTypeField;
	private javax.swing.JLabel name;
	private javax.swing.JTextField nameField;
	private javax.swing.JButton registerButton;
	private javax.swing.JButton resetButton;
	private javax.swing.JLabel title;
	// End of variables declaration//GEN-END:variables

}
