package view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Search extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Search */
	public Search() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		title = new javax.swing.JLabel();
		name = new javax.swing.JLabel();
		campusId1 = new javax.swing.JTextField();
		searchBtn1 = new javax.swing.JButton();
		name1 = new javax.swing.JLabel();
		campusId2 = new javax.swing.JTextField();
		searchBtn2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		title.setFont(new java.awt.Font("微软雅黑", 1, 14));
		title.setText("SEARCH");

		name.setFont(new java.awt.Font("微软雅黑", 1, 12));
		name.setText("CAMPUS ID");

		searchBtn1.setFont(new java.awt.Font("微软雅黑", 1, 12));
		searchBtn1.setText("SEARCH");
		searchBtn1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String campusId = campusId1.getText();
				if (!"".equals(campusId)) {
					getDefaultTableModel(campusId, false);
				} else {
					JOptionPane.showMessageDialog(null, "null input");
				}
				if (tableModel.getRowCount()>0) {
					SearchResult.searchResult = new SearchResult();
				}else {
					JOptionPane.showMessageDialog(null, "there is staff info fits your search condition");
				}
			}
		});

		name1.setFont(new java.awt.Font("微软雅黑", 1, 12));
		name1.setText("CAMPUS ID");

		searchBtn2.setFont(new java.awt.Font("微软雅黑", 1, 12));
		searchBtn2.setText("SEARCH");
		searchBtn2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String campusId = campusId2.getText();
				if (!"".equals(campusId)) {
					getDefaultTableModel(campusId);
				} else {
					JOptionPane.showMessageDialog(null, "null input");
				}
				if (tableModel.getRowCount()>0) {
					SearchResult.searchResult = new SearchResult();
				}else {
					JOptionPane.showMessageDialog(null, "there is no record fits your search condition");
				}
			}
		});

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel1.setText("STAFF INFO :");

		jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel2.setText("PARKING RECORD :");


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(name)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(campusId1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										83,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(searchBtn1).addGap(19, 19, 19))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(name1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(campusId2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										83,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(searchBtn2).addGap(19, 19, 19))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										87,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(179, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										129,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(137, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup().addGap(105, 105, 105)
								.addComponent(title)
								.addContainerGap(115, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(8, 8, 8)
								.addComponent(title)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(name)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		searchBtn1)
																.addComponent(
																		campusId1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addComponent(jLabel2)
								.addGap(21, 21, 21)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(name1)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		searchBtn2)
																.addComponent(
																		campusId2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(15, Short.MAX_VALUE)));

		pack();
		setVisible(true);
	}
	private void getDefaultTableModel(String campusId) {
		tableModel = new DefaultTableModel(new String[] {
				"CAMPUS ID", "MOTO NO.", "ENTER TIME", "EXIT TIME", "FEE" }, 0);
		try {
			BufferedReader reader = new BufferedReader(new FileReader(new File(
					"src/record.txt")));
			String staffInfo;
			while (!"".equals((staffInfo = reader.readLine()))&&staffInfo!=null) {
				String[] staffInfos = staffInfo.split("@");
				if (staffInfos[0].equals(campusId)) {
					tableModel.addRow(staffInfos);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	private void getDefaultTableModel(String campusId, boolean b) {
		tableModel = new DefaultTableModel(new String[] {
				"CAMPUS ID", "NAME", "MOTO NO.", "MOTO TYPE", "COLOR", "BILL" }, 0);
		try {
			BufferedReader reader = new BufferedReader(new FileReader(new File(
					"src/staff.txt")));
			String staffInfo;
			while (!"".equals((staffInfo = reader.readLine()))&&staffInfo!=null) {
				String[] staffInfos = staffInfo.split("@");
				if (staffInfos[0].equals(campusId)) {
					tableModel.addRow(staffInfos);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify
	public static Search search;
	public DefaultTableModel tableModel;
	private javax.swing.JTextField campusId1;
	private javax.swing.JTextField campusId2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel name;
	private javax.swing.JLabel name1;
	private javax.swing.JButton searchBtn1;
	private javax.swing.JButton searchBtn2;
	private javax.swing.JLabel title;
	// End of variables declaration//GEN-END:variables

}
